on:
  push:
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: chainguard-dev/actions/setup-chainctl@main
        with:
          environment: enforce.dev
          identity: 849bf3cd15c424f4babfc86cb606bb1569b0dbc8/844585f9dd79c40e
      - run: |
          docker pull alpine
          docker tag alpine registry.enforce.dev/849bf3cd15c424f4babfc86cb606bb1569b0dbc8/from-gha
          docker push registry.enforce.dev/849bf3cd15c424f4babfc86cb606bb1569b0dbc8/from-gha
